### ISSUE TITLE
Uguu.se support

### ISSUE THREAD

**Issue by tsdko** [Nyubis/Pomfshare#2]
Mainly because most files I share aren't supposed to remain there forever and I don't want them to take up space on neku's servers forever. Enabling randomname would be nice too.

**Comment by deavmi** [comment]
Was about to say this too. This would really be an awesome feature.

**Comment by Nyubis** [comment]
Done https://github.com/Nyubis/Pomfshare/commit/f6e38b26756c9be7a5972a91331d306a25d4a171

**Comment by deavmi** [comment]
Thanks. By now I have already forgotten what uguu.se is.

**Comment by deavmi** [comment]
Yay!

`http://a.uguu.se/kstobi.jpeg`
