### ISSUE TITLE
Uguu.se upload broken

### ISSUE THREAD

**Issue by 676339784** [Nyubis/Pomfshare#7]
Uguu.se upload returns a [<!DOCTYPE html>](https://a.pomf.cat/mgugkd.png), which I suspect is due to the [redesign of the site](http://pub.iotek.org/p/7aZqzwN.png) when a file is uploaded.

**Comment by Scrxtchy** [comment]
Have you updated?
aa41269

Just noticed lack of release here, I'll chuck something into my repository until then
https://github.com/Scrxtchy/Pomfshare/releases/tag/v0.5

**Comment by Nyubis** [comment]
Thanks for that, @Scrxtchy 
I've reformatted recently and I haven't got AndroidStudio set up again, so I can't make a release myself right now. I'll close this issue when I do.

**Comment by Nyubis** [comment]
Finally made it into a release, [grab it here](https://github.com/Nyubis/Pomfshare/releases/tag/v0.4.1).
